version: '3.8'

services:
  backend:
    image: tekechiregistry.azurecr.io/azure_app_backend:latest

  frontend:
    image: tekechiregistry.azurecr.io/azure_app_frontend:latest

  nginx:
    image: tekechiregistry.azurecr.io/azure_app_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
